Fix: use minified size in sourcemap mode
btd/rollup-plugin-visualizer pull request #164
Opened 2023-05-17 10:00 UTC by thoughtspile

Hi @btd! As discussed yesterday in #163, fixed sourcemap mode to correctly measure module size after minification. To address your concern about surrogate pairs, I collect actual `code` in the final chunk per-module instead of incrementing `renderedLength`.

Since we now have the precise code available in sourcemap mode, I also went ahead and allowed `gzipSize` and `brotliSize` in sourcemap mode. Compressed sizes are very close to ones in default mode.

Added a test case with terser, updated snapshots for both changes. Un-minified sourcemap sizes are 1 byte larger than `bundle.code[id]` because rollup trims trailing newline.

I wonder if we could remove non-sourcemap option altogether? It doesn't seem to have any benefits, and reports incorrect sizes.

Fixes #163

2023-06-04 10:41 UTC, thoughtspile commented
Hey @btd, did you have a chance to look through the changes? It's not too complicated, and should greatly improve the analysis.

2023-06-10 12:49 UTC, btd requested changes
Hi, sorry for taking so long. Super busy at work.
Overall feedback: with your changes you remove support of old 2.x rollup. I still support it, next you silent and removed feedback about gzip,brotli options with sourcemap.

2023-06-10 12:49 UTC, btd commented on plugin/index.ts
> -   * `gzipSize` and `brotliSize` does not make much sense with this option.
Why you removed this? You also disabled this in code.

2023-06-10 12:49 UTC, btd commented on plugin/index.ts
> +      const brotliSize = !!opts.brotliSize;
I would print a warning also. It is not good UX to just silently disable options.

2023-06-10 12:49 UTC, btd commented on plugin/index.ts
> -        code: string | null;
Please return this back. It is to support old 2.x version of rollup

2023-06-10 12:49 UTC, btd commented on plugin/index.ts
> -                return ModuleLengths({ id, renderedLength, code });
The same as above. Code was added only in the middle of 2.x (i support it)

2023-06-10 12:49 UTC, btd commented on plugin/index.ts
> +              .map(([id, { code }]) => ModuleLengths({ id, code: code || "" }))
The same as above

2023-06-10 12:49 UTC, btd commented on plugin/sourcemap.ts
> +      modules[id].code += code[i];
There is no reason to try to combine code there. gzip and brotli sizes disabled for it. To get length need to get code point and get its length as surrogate pair

2023-06-10 12:49 UTC, btd commented on test/__snapshots__/gh59.test.ts.snap
> +    brotli: 17
This does not make sense at all

2023-11-24 15:11 UTC, closed without merging